services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
     - ./:/app/
    depends_on:
      - database
  database:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
  redis:
    image: redis:7
    ports:
      - "6379:6379"