services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    command:
      - poetry
      - run
      - uvicorn
      - bartrify.asgi:application
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload
      - --reload-dir
      - /app
      - --reload-include
      - "*.py"
      - --reload-include
      - "*.html"
      - --reload-include
      - "*.css"
      - --reload-include
      - "*.js"

    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
     - ./:/app/
    depends_on:
      - database
  database:
    image: postgres:17-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080