# Generated by Django 5.2.1 on 2025-06-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('IT_SUPPORT', 'IT Support & Troubleshooting'), ('GRAPHIC_DESIGN', 'Graphic Design & Branding'), ('WEB_DEV', 'Web Development & Design'), ('LANG_TUTOR', 'Language Tutoring'), ('HOME_REPAIR', 'Home Repair & Maintenance'), ('CLEANING', 'Cleaning Services'), ('PET_SITTING', 'Pet Sitting & Walking'), ('PHOTOGRAPHY', 'Photography & Editing'), ('CONSULTING', 'Business Consulting'), ('FITNESS_COACH', 'Fitness Coaching'), ('EDUCATION', 'Education & Tutoring'), ('HANDICRAFTS', 'Handicrafts & Custom Goods')], max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='desired_category',
            field=models.CharField(blank=True, choices=[('IT_SUPPORT', 'IT Support & Troubleshooting'), ('GRAPHIC_DESIGN', 'Graphic Design & Branding'), ('WEB_DEV', 'Web Development & Design'), ('LANG_TUTOR', 'Language Tutoring'), ('HOME_REPAIR', 'Home Repair & Maintenance'), ('CLEANING', 'Cleaning Services'), ('PET_SITTING', 'Pet Sitting & Walking'), ('PHOTOGRAPHY', 'Photography & Editing'), ('CONSULTING', 'Business Consulting'), ('FITNESS_COACH', 'Fitness Coaching'), ('EDUCATION', 'Education & Tutoring'), ('HANDICRAFTS', 'Handicrafts & Custom Goods')], max_length=100, null=True),
        ),
    ]
