# Generated by Django 5.2.1 on 2025-06-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_upload',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
