# Generated by Django 5.2.1 on 2025-06-24 03:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_user_avatar_upload_user_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_upload',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_avatar_path),
        ),
    ]
