# Generated by Django 5.2.1 on 2025-06-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_review_options_review_request_review_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='review',
            name='request',
        ),
        migrations.RemoveField(
            model_name='review',
            name='service',
        ),
    ]
