# Generated by Django 5.2.1 on 2025-06-27 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_review_options_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.servicerequest'),
        ),
    ]
