# Generated by Django 5.2.1 on 2025-06-27 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_service_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='offered_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offered_requests', to='core.service'),
        ),
    ]
