### REGISTER
POST http://localhost:8000/api/auth/signup/
Content-Type: application/json

{
  "username": "traderjoe",
  "email": "joe@example.com",
  "password": "SuperSecure123!"
}

###

### LOGIN
POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
  "username": "traderjoe",
  "password": "SuperSecure123!"
}

###
# access token from login response and use it here
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ5MDY0NDM2LCJpYXQiOjE3NDkwNjQxMzYsImp0aSI6ImM1YWUwMTkwNjRhMDQ2NDdhMzY1OWJkNjA2MjUwOGQzIiwidXNlcl9pZCI6MX0.cL_gwsZ9GDed3VUcS1CdfjXRQw5Eytj4JALepqyzO84


### GET MY PROFILE
GET http://localhost:8000/api/users/me/
Authorization: Bearer {{access_token}}

###

### UPDATE MY PROFILE
PATCH http://localhost:8000/api/users/me/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "bio": "I swap vintage guitars for rrwrwf",
  "location": "Amsterdam"
}

###

### GET PUBLIC PROFILE (replace 1 with a real user ID)
GET http://localhost:8000/api/users/1/


### Create a service
POST http://localhost:8000/api/services/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "title": "Dog Walking",
  "description": "I'll walk your dog for an hour. Happy puppers guaranteed.",
  "category": "Pet Services",
  "price": 15.00
}

### Get all services (feed)
GET http://localhost:8000/api/services/


### View dashboard
GET http://localhost:8000/api/users/dashboard/
Authorization: Bearer {{access_token}}
